stripe.secret-key=sk_test_51TGxjKF0TakR6EP5D9IQCDMHh8AbwzF9yEqedPOyrL3560YCFDjNETyt7Krs08PCk98DL2m6KIfhPz0kBsLnKa3j00n3XOFiHz
stripe.webhook-secret=
stripe.currency=cad
app.payment.security-deposit=200.00
